exports.gmailinfo = {
  USEREMAIL: process.env.USEREMAIL,
  PERSONALEMAIL: process.env.PERSONALEMAIL,
  CLIENTID: process.env.CLIENTID,
  CLIENTSECRET: process.env.CLIENTSECRET,
  ACCESSTOKEN: process.env.ACCESSTOKEN,
  REFRESHTOKEN: process.env.REFRESHTOKEN,
  CAPTCHASECRETKEY: process.env.CAPTCHASECRETKEY,
};